version: "3"
services:
  app:
    build: .
    environment: 
      USERNAME: "kannan"
      PASSWORD: "kannanpass"
      HOST: "mongo"
      MONGO_PORT: "27017"
    ports:
      - "3000:3000"
    depends_on: 
      - mongo
  
  mongo:
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_USERNAME: "kannan"
      MONGO_INITDB_ROOT_PASSWORD: "kannanpass"
    volumes:
      - mongo_data:/db/data


volumes:
  mongo_data: